Repository joaovitoriasilva/endurain, pull requests merged in 2025-07, with the labels that each got.

#229 Align doc to the docker-compose example and fix link to .env file
  docs/getting-started/getting-started.md
Labels: documentation

#212 Add support for gzipped activity files
  backend/app/activities/activity/utils.py
  frontend/app/src/views/HomeView.vue
Labels: enhancement

#224 feat : choose first day of the week
  backend/app/main.py
  backend/app/users/user/models.py
  backend/app/users/user/schema.py
  frontend/app/src/services/usersService.js
  frontend/app/src/stores/authStore.js
  frontend/app/src/utils/dateTimeUtils.js
  frontend/app/src/utils/summaryUtils.js
  frontend/app/src/views/SummaryView.vue
Labels: enhancement

#235 Add support for tcx files
  .gitignore
  backend/app/activities/activity/crud.py
  backend/app/activities/activity/utils.py
  backend/app/tcx/__init__.py
  backend/app/tcx/utils.py
  backend/poetry.lock
  backend/pyproject.toml
  frontend/app/src/i18n/us/homeView.json
  frontend/app/src/views/HomeView.vue
Labels: enhancement

#239 Bulk import documentation work
  docs/getting-started/advanced-started.md
  frontend/app/src/i18n/us/components/settings/settingsIntegrationsZoneComponent.json
Labels: documentation, enhancement
