Repository joaovitoriasilva/endurain, pull requests merged in 2025-06, with the labels that each got.

#194 support ski and snowboard as gear
  backend/app/activities/activity_streams/dependencies.py
  backend/app/alembic/versions/bd59252fe91f_v0_13_0_migration.py
  backend/app/core/dependencies.py
  backend/app/gears/dependencies.py
  backend/app/gears/models.py
  backend/app/users/user_default_gear/models.py
  backend/app/users/user_default_gear/schema.py
  backend/app/users/user_default_gear/utils.py
  docs/developer-guide.md
  docs/index.md
  frontend/app/src/assets/avatar/skis1.png
  frontend/app/src/assets/avatar/snowboard1.png
  frontend/app/src/components/Gears/GearsAddEditGearModalComponent.vue
  frontend/app/src/components/Gears/GearsListComponent.vue
  frontend/app/src/components/Settings/SettingsUserProfileZone.vue
  frontend/app/src/i18n/de/components/gears/gearsAddEditGearModalComponent.json
  frontend/app/src/i18n/de/components/gears/gearsListComponent.json
  frontend/app/src/i18n/de/gears/gearView.json
  frontend/app/src/i18n/us/components/gears/gearsAddEditGearModalComponent.json
  frontend/app/src/i18n/us/components/gears/gearsListComponent.json
  frontend/app/src/i18n/us/components/settings/settingsUserProfileZoneComponent.json
  frontend/app/src/i18n/us/gears/gearView.json
  frontend/app/src/i18n/us/searchView.json
  frontend/app/src/views/Gears/GearView.vue
  frontend/app/src/views/SearchView.vue
Labels: enhancement

#203 Updated hosting guide
  .env.example
  docker-compose.yml-multiple-backends.example
  docker-compose.yml.example
  docs/getting-started/advanced-started.md
  docs/getting-started/getting-started.md
  mkdocs.yml
Labels: documentation

#219 Fix error that occurs while handling the error ('module' object is not callable)
  backend/app/activities/activity_streams/crud.py
Labels: bug
